# Spring Boot 应用配置
spring:
  application:
    name: My Spring Boot Application # 您的应用名称
  datasource:
    # MySQL 8.0 数据库连接 URL
    # 请将 'your_database_name' 替换为你的实际数据库名称。
    # 这些参数推荐用于 MySQL 8+，以正确处理时区和字符编码。
    url: jdbc:mysql://127.0.0.1:3306/your_database_name?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    # 替换为你的 MySQL 用户名和密码
    username: root
    password: password
    # MySQL Connector/J 8+ 的驱动类名
    driver-class-name: com.mysql.cj.jdbc.Driver

# Mybatis 配置
mybatis:
  # Mapper XML 文件路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 启用 SQL 语句在控制台的日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 自动将数据库中的下划线命名（underscore_case）映射到 Java 对象中的驼峰命名（camelCase）
    map-underscore-to-camel-case: true

# SpringDoc OpenAPI 配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html # 访问 Swagger UI 的路径，默认为 /swagger-ui.html，可自定义
    disable-swagger-default-url: true # 禁用默认的 petstore 示例
  api-docs:
    path: /v3/api-docs # OpenAPI 3 JSON 规范的路径，默认为 /v3/api-docs
  default-produces-media-type: application/json # 默认的生产媒体类型
  info:
    title: "${spring.application.name} API Documentation" # API 文档标题，引用应用名称
    description: "这是我的 Spring Boot 项目的 API 文档。提供所有后端接口的详细说明和测试功能。" # API 描述
    version: "1.0.0" # API 版本
    terms-of-service: "http://example.com/terms/" # 服务条款链接 (可选)
    contact: # 联系信息
      name: "您的名字"
      url: "http://yourwebsite.com"
      email: "youremail@example.com"
    license: # 许可证信息
      name: "Apache 2.0"
      url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  external-docs: # 外部文档链接 (可选)
    description: "更多信息请访问我们的官网"
    url: "http://yourcompany.com"

# 高德地图 API 配置
amap:
  key: b76a53fff091a12f2807eba6b206febd # 你的高德地图 API 密钥
